In [2]:
import torch
import numpy as np

In [4]:
# two rank 2 matrix with length 2 each
t1 = torch.tensor([
    [1,2],
    [3,4]
],dtype = torch.float32)
t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype = torch.float32)

In [5]:
# it follows the matrices rule that the matrices must have same shape
# to conduct an elementwise operation.
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [10]:
# all arithmetic operations are elementwise operations
# scalar operations are carried out using broadcasting.
# what it essentailly does is create a tensor with the same shape the one it is to be performed on and carries out the operation.
# let us see an example to further understand this.
t1 = torch.tensor([
    [1,1],
    [1,1]
],dtype = torch.float32)

t2 = torch.tensor([2,4], dtype = torch.float32)

In [11]:
t1.shape

torch.Size([2, 2])

In [12]:
t2.shape

torch.Size([2])

In [15]:
# t1 + t2 ??? 
# PyTorch will use braodcasting to change the lower rank matrix,
# to conform with the higher rank matrix satifying the rule of same shape for elemntwise operations.
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [16]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

In [17]:
# comparison operations will follow the set theory and return a tensor of the same shape replcaed with
# 1 where the elements are equal and
# 0 where they are not

t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype = torch.float32)

In [18]:
t.eq(0)

tensor([[1, 0, 0],
        [0, 1, 0],
        [1, 0, 1]], dtype=torch.uint8)

In [19]:
t.gt(0)

tensor([[0, 1, 1],
        [1, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)

In [20]:
t.lt(0)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [21]:
# greater than equal
t.ge(0)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [23]:
# less than equal
# here we can see that broadcasting has been used to make the scalar 7 to become
"""
[0,5,7],    [7,7,7],           [1, 1, 1],
[6,0,7], == [7,7,7],     =     [1, 1, 1],
[0,8,0]     [7,7,7]            [1, 0, 1] 
"""
t.le(7)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)