In [1]:
import torch

In [4]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype = torch.float32)

In [5]:
t.size()

torch.Size([3, 4])

In [6]:
t.shape

torch.Size([3, 4])

In [8]:
len(t.shape)

2

In [10]:
t.numel()

12

In [11]:
# tensor reshaping must follow the m*n rule 
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [13]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [14]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [15]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [17]:
# we can also change the rank using 3 parameters.
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [18]:
# The squeeze and unsqeeze functions can be used to reshape the tensors as well
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [19]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [20]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [28]:
# Flatten operation just means converting the tensor to a lower rank than what you startet with.
# Passing -1 tells pyTorch to figure out the product which will be correct for an m*n array where m=1 
# based on the number of elements in the tensor.
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [22]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [27]:
t.reshape(12)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])